# Generated by Django 5.1.7 on 2025-03-20 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_book', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='driveaxlemodel',
            options={'verbose_name': 'Модель ведущего моста', 'verbose_name_plural': 'Модели ведущих мостов'},
        ),
        migrations.AlterModelOptions(
            name='enginemodel',
            options={'verbose_name': 'Модель двигателя', 'verbose_name_plural': 'Модели двигателей'},
        ),
        migrations.AlterModelOptions(
            name='equipmentmodel',
            options={'verbose_name': 'Модель техники', 'verbose_name_plural': 'Модели техники'},
        ),
        migrations.AlterModelOptions(
            name='failedcomponent',
            options={'verbose_name': 'Узел отказа', 'verbose_name_plural': 'Узлы отказов'},
        ),
        migrations.AlterModelOptions(
            name='maintenancetype',
            options={'verbose_name': 'Вид ТО', 'verbose_name_plural': 'Вид ТО'},
        ),
        migrations.AlterModelOptions(
            name='recoverymethod',
            options={'verbose_name': 'Способ восстановления', 'verbose_name_plural': 'Способы восстановления'},
        ),
        migrations.AlterModelOptions(
            name='servicecompany',
            options={'verbose_name': 'Сервисная компания', 'verbose_name_plural': 'Сервисные компании'},
        ),
        migrations.AlterModelOptions(
            name='steeringaxlemodel',
            options={'verbose_name': 'Модель управляемого моста', 'verbose_name_plural': 'Модели управляемых мостов'},
        ),
        migrations.AlterModelOptions(
            name='technicalmaintenance',
            options={'verbose_name': 'ТО', 'verbose_name_plural': 'ТО'},
        ),
        migrations.AlterModelOptions(
            name='transmissionmodel',
            options={'verbose_name': 'Модель трансмиссии', 'verbose_name_plural': 'Модели трансмиссии'},
        ),
    ]
