# Generated by Django 5.1.7 on 2025-03-21 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_book', '0002_alter_car_client'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='none', max_length=155, verbose_name='Имя/Название компании'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('client', 'Клиент'), ('service', 'Сервисная организация'), ('manager', 'Менеджер')], default='client', max_length=20, verbose_name='Роль'),
        ),
    ]
